# Generated by Django 6.0.5 on 2026-06-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_testcase_description_testcase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
